/*
 * Copyright 2026 glomdom
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using System.Diagnostics;
using System.Linq;
using System.Text;
using BinaryWizard.Analysis;
using BinaryWizard.Models;
using BinaryWizard.Segmenting;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BinaryWizard.Emission;

internal static class CodeBuilder {
    internal static void Generate(SourceProductionContext spc, ClassSerializationMeta? meta) {
        if (meta is null) return;

        foreach (var diag in meta.Diagnostics) {
            spc.ReportDiagnostic(diag);
        }

        if (meta.Diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error)) {
            return;
        }

        Debug.WriteLine($"Starting code generation for {meta.ClassName}");

        var bodyBuilder = new StringBuilder();
        var hasNamespace = !string.IsNullOrEmpty(meta.Namespace);
        var baseIndent = hasNamespace ? "    " : "";
        var bodyIndent = baseIndent + "        ";

        var segmentCount = 0;

        foreach (var seg in meta.Segments) {
            switch (seg) {
                case FixedSegment fixedSeg: ProcessFixedSegment(++segmentCount, fixedSeg, bodyBuilder, bodyIndent); break;
                case DynamicSegment dynSeg: ProcessDynamicSegment(dynSeg, bodyBuilder, bodyIndent); break;
                case NestedObjectSegment nestedSeg: bodyBuilder.AppendLine($"{bodyIndent}result.{nestedSeg.FieldName} = {nestedSeg.TypeName}.FromBinary(reader);"); break;
            }
        }

        var code = $$"""
                     // <autogenerated/>
                     using System;
                     using System.IO;
                     using System.Buffers.Binary;

                     {{(hasNamespace ? $"namespace {meta.Namespace}\n{{" : "")}}
                     {{baseIndent}}partial {{meta.Kind}} {{meta.ClassName}} {
                     {{baseIndent}}    public static {{meta.ClassName}} FromBinary(System.IO.BinaryReader reader) {
                     {{baseIndent}}        var result = new {{meta.ClassName}}();

                     {{bodyBuilder}}
                     {{baseIndent}}        return result;
                     {{baseIndent}}    }
                     {{baseIndent}}}
                     {{(hasNamespace ? "}" : "")}}
                     """;

        spc.AddSource($"BinarySerializable_{meta.ClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    private static void ProcessDynamicSegment(DynamicSegment seg, StringBuilder sb, string indent) {
        foreach (var field in seg.Fields) {
            var elementBytes = field.TypeModel.InnerType!.GetByteSize();
            var bufferName = $"__{field.Name}_buf";

            sb.AppendLine($$"""
                            {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[result.{{seg.LengthReferenceFieldName}}];
                            {{indent}}Span<byte> {{bufferName}} = stackalloc byte[{{elementBytes}} * result.{{seg.LengthReferenceFieldName}}];
                            {{indent}}if (reader.Read({{bufferName}}) < {{elementBytes}} * result.{{seg.LengthReferenceFieldName}}) throw new EndOfStreamException();
                            {{indent}}for (var i = 0; i < result.{{seg.LengthReferenceFieldName}}; i++) {
                            {{indent}}    result.{{field.Name}}[i] = {{field.TypeModel.Type.GetBinaryPrimitiveReader()}}({{bufferName}}.Slice(i * {{elementBytes}}, {{elementBytes}}));
                            {{indent}}}
                            """);
        }
    }

    private static void ProcessFixedSegment(int segmentIndex, FixedSegment seg, StringBuilder sb, string indent) {
        var bufName = $"__buf_{segmentIndex}";
        var localOffset = 0;

        sb.AppendLine($"""
                       {indent}Span<byte> {bufName} = stackalloc byte[{seg.Bytes}];
                       {indent}if (reader.Read({bufName}) < {seg.Bytes}) throw new EndOfStreamException();
                       """);

        foreach (var field in seg.Fields) {
            if (field.TypeModel.IsFixedArray) {
                var elementBytes = field.TypeModel.InnerType!.GetByteSize();

                sb.AppendLine($$"""
                                {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[{{field.TypeModel.FixedArraySize!.Value}}];
                                {{indent}}for (var i = 0; i < {{field.TypeModel.FixedArraySize}}; i++) {
                                {{indent}}    result.{{field.Name}}[i] = {{field.TypeModel.Type.GetBinaryPrimitiveReader()}}({{bufName}}.Slice({{localOffset}} + ({{elementBytes}} * i), {{elementBytes}}));
                                {{indent}}}
                                """);

                localOffset += elementBytes * field.TypeModel.FixedArraySize!.Value;

                continue;
            }

            sb.AppendLine($"{indent}result.{field.Name} = {field.TypeModel.Type.GetBinaryPrimitiveReader()}({bufName}.Slice({localOffset}, {field.ByteSize}));");

            if (field.HasMagic) {
                var magicStr = field.Magic;
                long magicExpectedValue = 0;

                // TODO: Support endianness
                for (var i = 0; i < magicStr.Length; i++) {
                    magicExpectedValue |= (long)magicStr[i] << i * 8;
                }

                sb.AppendLine(
                    $"{indent}if (result.{field.Name} != {magicExpectedValue}) throw new InvalidDataException(\"Magic validation failed for {field.Name}. Expected {magicStr}.\");");
            }

            localOffset += field.ByteSize;
        }
    }
}