/*
 * Copyright 2025 glomdom
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using BinaryWizard.Model;
using BinaryWizard.Segmenting;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BinaryWizard;

[Generator]
public class Generator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var assembly = Assembly.GetExecutingAssembly();
        var resourceNames = assembly.GetManifestResourceNames();

        context.RegisterPostInitializationOutput(ctx => {
            foreach (var resourceName in resourceNames) {
                using var stream = assembly.GetManifestResourceStream(resourceName);
                if (stream is null) continue;

                using var reader = new StreamReader(stream);
                var source = reader.ReadToEnd();

                var hintParts = Path.GetFileNameWithoutExtension(resourceName).Split('.');
                var hintName = hintParts[hintParts.Length - 1];

                ctx.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        });

        const string fullyQualifiedAttributeName = $"{Constants.Codegen.Namespace}.{Constants.Attributes.BinarySerializable}";

        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedAttributeName,
                predicate: static (s, _) => s is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => ctx)
            .WithTrackingName("BinarySerializableGeneration");

        context.RegisterSourceOutput(
            provider,
            GenerateCode
        );
    }

    private void GenerateCode(SourceProductionContext spc, GeneratorAttributeSyntaxContext ctx) {
        Debug.WriteLine("Starting code generation");

        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return;

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString();

        var declarationName = classSymbol.Name;
        var kind = classSymbol.TypeKind == TypeKind.Class ? "class" : "struct";

        var segmentManager = new SegmentManager();
        var bodyBuilder = new StringBuilder();

        var hasNamespace = !string.IsNullOrEmpty(namespaceName);
        var baseIndent = hasNamespace ? "    " : "";
        var bodyIndent = baseIndent + "        ";

        BuildReadStatements(spc, segmentManager, classSymbol, bodyBuilder, bodyIndent);

        var code = $$"""
                     // <autogenerated/>
                     using System;
                     using System.IO;
                     using System.Buffers.Binary;

                     {{(hasNamespace ? $"namespace {namespaceName}\n{{" : "")}}
                     {{baseIndent}}partial {{kind}} {{declarationName}}
                     {{baseIndent}}{
                     {{baseIndent}}    public static {{declarationName}} FromBinary(System.IO.BinaryReader reader)
                     {{baseIndent}}    {
                     {{baseIndent}}        var result = new {{declarationName}}();

                     {{bodyBuilder}}
                     {{baseIndent}}        return result;
                     {{baseIndent}}    }
                     {{baseIndent}}}
                     {{(hasNamespace ? "}" : "")}}
                     """;

        spc.AddSource($"BinarySerializable_{declarationName}.g.cs", SourceText.From(code, Encoding.UTF8));
        Debug.WriteLine($"Created read method for {declarationName}");
    }

    private void BuildReadStatements(
        SourceProductionContext spc,
        SegmentManager segmentManager,
        INamedTypeSymbol classSymbol,
        StringBuilder sb,
        string indent
    ) {
        var fields = classSymbol.GetMembers().OfType<IFieldSymbol>();
        var segmentCount = 0;

        foreach (var field in fields) {
            var fieldType = field.Type;

            if (IsPrimitiveLike(fieldType)) {
                var fieldDef = new FieldDef(field.Name, fieldType) {
                    ByteSize = GetByteSizeForPrimitive(fieldType),
                };

                segmentManager.AddField(fieldDef);
                DebugUtilities.CreatedFieldDef(fieldDef);
            } else if (IsArrayLike(fieldType, out var arrSymbol)) {
                if (arrSymbol.Rank != 1) throw new NotSupportedException("Arrays which have more than 1 dimension are not supported.");

                var binaryArrayAttr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "BinaryArrayAttribute");
                if (binaryArrayAttr is null) {
                    ReportArrayIsMissingAttribute(spc, field);

                    continue;
                }

                if (!AreAnyNamedArgsProvided(binaryArrayAttr, "Size", "SizeMember")) {
                    ReportArrayIsMissingSizeArgument(spc, field);

                    continue;
                }

                if (AreAllNamedArgsProvided(binaryArrayAttr, "Size", "SizeMember")) {
                    ReportArrayHasConflictingSizeArguments(spc, field);

                    continue;
                }

                var fieldDef = new FieldDef(field.Name, arrSymbol.ElementType) {
                    TypeModel = {
                        InnerType = arrSymbol.ElementType,
                        InnerTypeByteSize = GetByteSizeForPrimitive(arrSymbol.ElementType),
                    },
                };

                if (TryGetNamedArg(binaryArrayAttr, "Size", out var arrSize)) {
                    var arrSizeValue = (int)arrSize.Value!;
                    fieldDef.ByteSize = arrSizeValue * GetByteSizeForPrimitive(arrSymbol.ElementType);
                    fieldDef.TypeModel.FixedArraySize = arrSizeValue;

                    DebugUtilities.CreatedFieldDef(fieldDef);
                    segmentManager.AddField(fieldDef);
                } else if (TryGetNamedArg(binaryArrayAttr, "SizeMember", out var sizeMember)) {
                    var arrSizeRef = (string)sizeMember.Value!;
                    fieldDef.ByteSize = -1;

                    DebugUtilities.CreatedFieldDef(fieldDef);
                    segmentManager.AddField(fieldDef, arrSizeRef);
                }
            } else if (HasBinarySerializableAttribute(fieldType)) {
                FlushSegments();
                sb.AppendLine($"{indent}result.{field.Name} = {fieldType.Name}.FromBinary(reader);");

                Debug.WriteLine("Built statements for nested object");
            } else {
                ReportUnmarkedSerializableForField(spc, field);
            }
        }

        FlushSegments();

        return;

        void FlushSegments() {
            var segments = segmentManager.Commit();
            foreach (var seg in segments) {
                switch (seg) {
                    case FixedSegment fixedSeg: ProcessFixedSegment(++segmentCount, fixedSeg, sb, indent); break;
                    case DynamicSegment dynSeg: ProcessDynamicSegment(dynSeg, sb, indent); break;
                }
            }

            segmentManager.Clear();
        }
    }

    private void ProcessDynamicSegment(DynamicSegment seg, StringBuilder sb, string indent) {
        foreach (var field in seg.Fields) {
            var elementBytes = GetByteSizeForPrimitive(field.TypeModel.InnerType!);
            var bufferName = $"__{field.Name}_buf";

            sb.AppendLine($$"""
                            {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[result.{{seg.LengthReferenceFieldName}}];
                            {{indent}}Span<byte> {{bufferName}} = stackalloc byte[{{elementBytes}}];
                            {{indent}}for (var i = 0; i < result.{{seg.LengthReferenceFieldName}}; i++) {
                            {{indent}}    if (reader.Read({{bufferName}}) < {{elementBytes}}) throw new EndOfStreamException();
                            {{indent}}    result.{{field.Name}}[i] = {{GetBinaryPrimitiveReaderForPrimitive(field.TypeModel.Type)}}({{bufferName}});
                            {{indent}}}
                            """);
        }
    }

    private void ProcessFixedSegment(int segmentIndex, FixedSegment seg, StringBuilder sb, string indent) {
        var bufName = $"__buf_{segmentIndex}";
        var localOffset = 0;

        sb.AppendLine($"""
                       {indent}Span<byte> {bufName} = stackalloc byte[{seg.Bytes}];
                       {indent}if (reader.Read({bufName}) < {seg.Bytes}) throw new EndOfStreamException();
                       """);

        foreach (var field in seg.Fields) {
            if (field.TypeModel.IsFixedArray) {
                var elementBytes = GetByteSizeForPrimitive(field.TypeModel.InnerType!);

                sb.AppendLine($$"""
                                {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[{{field.TypeModel.FixedArraySize!.Value}}];
                                {{indent}}for (var i = 0; i < {{field.TypeModel.FixedArraySize}}; i++) {
                                {{indent}}    result.{{field.Name}}[i] = {{GetBinaryPrimitiveReaderForPrimitive(field.TypeModel.Type)}}({{bufName}}.Slice({{localOffset}} + ({{elementBytes}} * i), {{elementBytes}}));
                                {{indent}}}
                                """);

                localOffset += elementBytes * field.TypeModel.FixedArraySize!.Value;
                continue;
            }

            sb.AppendLine($"{indent}result.{field.Name} = {GetBinaryPrimitiveReaderForPrimitive(field.TypeModel.Type)}({bufName}.Slice({localOffset}, {field.ByteSize}));");

            localOffset += field.ByteSize;
        }
    }

    private string GetBinaryPrimitiveReaderForPrimitive(ITypeSymbol sym) {
        return sym.SpecialType switch {
            SpecialType.System_Int32 => "BinaryPrimitives.ReadInt32LittleEndian",

            _ => throw new InvalidOperationException(
                $"Unexpected type {sym.SpecialType} occurred in GetBinaryPrimitiveReaderForPrimitive"
            ),
        };
    }

    private static bool HasBinarySerializableAttribute(ITypeSymbol sym) => HasAttribute(sym, "BinarySerializableAttribute");
    private static bool HasAttribute(ITypeSymbol sym, string attrName) => sym.GetAttributes().Any(a => a.AttributeClass?.Name == attrName);

    private int GetByteSizeForPrimitive(ITypeSymbol primitive) {
        return primitive.SpecialType switch {
            SpecialType.System_Boolean => 1,
            SpecialType.System_Char => 1,
            SpecialType.System_SByte => 1,
            SpecialType.System_Byte => 1,
            SpecialType.System_Int16 => 2,
            SpecialType.System_UInt16 => 2,
            SpecialType.System_Int32 => 4,
            SpecialType.System_UInt32 => 4,
            SpecialType.System_Int64 => 8,
            SpecialType.System_UInt64 => 8,
            SpecialType.System_Decimal => 16,
            SpecialType.System_Double => 32,

            _ => throw new InvalidOperationException("Unexpected case encountered."),
        };
    }

    private static bool IsPrimitiveLike(ITypeSymbol symbol) {
        return symbol.SpecialType switch {
            SpecialType.System_Boolean or
                SpecialType.System_Byte or
                SpecialType.System_SByte or
                SpecialType.System_Int16 or
                SpecialType.System_UInt16 or
                SpecialType.System_Int32 or
                SpecialType.System_UInt32 or
                SpecialType.System_Int64 or
                SpecialType.System_UInt64 or
                SpecialType.System_Single or
                SpecialType.System_Double or
                SpecialType.System_Char or
                SpecialType.System_String or
                SpecialType.System_Decimal => true,

            _ => false,
        };
    }

    private static bool IsArrayLike(ITypeSymbol symbol, [NotNullWhen(true)] out IArrayTypeSymbol? arraySymbol) {
        if (symbol is IArrayTypeSymbol arr) {
            arraySymbol = arr;
            return true;
        }

        arraySymbol = null;
        return false;
    }

    private static bool AreAllNamedArgsProvided(AttributeData attr, params string[] names) {
        return attr.NamedArguments.Length != 0 && names.Select(name => attr.NamedArguments.Any(pair => pair.Key == name)).All(found => found);
    }

    private static bool AreAnyNamedArgsProvided(AttributeData attr, params string[] names) {
        return attr.NamedArguments.Length != 0 && names.Any(name => attr.NamedArguments.Any(pair => pair.Key == name));
    }

    private static bool TryGetNamedArg(
        AttributeData attr,
        string name,
        out TypedConstant typedConstant
    ) {
        foreach (var pair in attr.NamedArguments.Where(pair => pair.Key == name)) {
            typedConstant = pair.Value;
            return true;
        }

        typedConstant = default;
        return false;
    }

    private void ReportArrayHasConflictingSizeArguments(SourceProductionContext spc, IFieldSymbol field) {
        var location = GetVariableDeclaratorNameLocation(field);

        spc.ReportDiagnostic(Diagnostic.Create(
            Diagnostics.ArrayHasConflictingSizeArguments,
            location,
            field.Name
        ));
    }

    private void ReportArrayIsMissingSizeArgument(SourceProductionContext spc, IFieldSymbol field) {
        var location = GetVariableDeclaratorNameLocation(field);

        spc.ReportDiagnostic(Diagnostic.Create(
            Diagnostics.MarkedArraylikeHasNoSizeOrSizeProviderRule,
            location,
            field.Name
        ));
    }

    private void ReportArrayIsMissingAttribute(SourceProductionContext spc, IFieldSymbol field) {
        var location = GetVariableDeclaratorNameLocation(field);

        spc.ReportDiagnostic(Diagnostic.Create(
            Diagnostics.ArrayHasNoBinaryArrayAttributeRule,
            location,
            field.Name
        ));
    }

    private void ReportUnmarkedSerializableForField(SourceProductionContext spc, IFieldSymbol field) {
        var location = GetVariableDeclaratorLocation(field);

        spc.ReportDiagnostic(Diagnostic.Create(
            Diagnostics.MissingBinarySerializableAttributeRule,
            location,
            field.Type.Name
        ));
    }

    private Location GetVariableDeclaratorLocation(IFieldSymbol field) {
        var fieldSyntaxRef = field.DeclaringSyntaxReferences.FirstOrDefault();
        var fieldSyntax = fieldSyntaxRef?.GetSyntax() as VariableDeclaratorSyntax;
        if (fieldSyntax?.Parent is not VariableDeclarationSyntax varDecl) throw new Exception("Field parent is not a variable declaration.");

        return varDecl.Type.GetLocation();
    }

    private Location GetVariableDeclaratorNameLocation(IFieldSymbol field) {
        var fieldSyntaxRef = field.DeclaringSyntaxReferences.FirstOrDefault();
        if (fieldSyntaxRef is null) throw new Exception("No syntax reference found for field.");

        return fieldSyntaxRef.GetSyntax() is not VariableDeclaratorSyntax fieldSyntax
            ? throw new Exception("Field syntax is not a VariableDeclaratorSyntax.")
            : fieldSyntax.Identifier.GetLocation();
    }
}