/*
 * Copyright 2026 glomdom
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using BinaryWizard.Analysis;
using BinaryWizard.Diagnostics;
using BinaryWizard.Model;
using BinaryWizard.Segmenting;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BinaryWizard;

[Generator]
public class Generator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var assembly = Assembly.GetExecutingAssembly();
        var resourceNames = assembly.GetManifestResourceNames();

        context.RegisterPostInitializationOutput(ctx => {
            foreach (var resourceName in resourceNames) {
                using var stream = assembly.GetManifestResourceStream(resourceName);
                if (stream is null) continue;

                using var reader = new StreamReader(stream);
                var source = reader.ReadToEnd();

                var hintParts = Path.GetFileNameWithoutExtension(resourceName).Split('.');
                var hintName = hintParts[hintParts.Length - 1];

                ctx.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        });

        const string fullyQualifiedAttributeName = $"{Constants.Codegen.Namespace}.{Constants.Attributes.BinarySerializable}";

        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedAttributeName,
                predicate: static (s, _) => s is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => ctx)
            .WithTrackingName("BinarySerializableGeneration");

        context.RegisterSourceOutput(
            provider,
            GenerateCode
        );
    }

    private void GenerateCode(SourceProductionContext spc, GeneratorAttributeSyntaxContext ctx) {
        Debug.WriteLine("Starting code generation");

        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return;

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString();

        var declarationName = classSymbol.Name;
        var kind = classSymbol.TypeKind == TypeKind.Class ? "class" : "struct";

        var segmentManager = new SegmentManager();
        var bodyBuilder = new StringBuilder();

        var hasNamespace = !string.IsNullOrEmpty(namespaceName);
        var baseIndent = hasNamespace ? "    " : "";
        var bodyIndent = baseIndent + "        ";

        BuildReadStatements(spc, segmentManager, classSymbol, bodyBuilder, bodyIndent);

        var code = $$"""
                     // <autogenerated/>
                     using System;
                     using System.IO;
                     using System.Buffers.Binary;

                     {{(hasNamespace ? $"namespace {namespaceName}\n{{" : "")}}
                     {{baseIndent}}partial {{kind}} {{declarationName}}
                     {{baseIndent}}{
                     {{baseIndent}}    public static {{declarationName}} FromBinary(System.IO.BinaryReader reader)
                     {{baseIndent}}    {
                     {{baseIndent}}        var result = new {{declarationName}}();

                     {{bodyBuilder}}
                     {{baseIndent}}        return result;
                     {{baseIndent}}    }
                     {{baseIndent}}}
                     {{(hasNamespace ? "}" : "")}}
                     """;

        spc.AddSource($"BinarySerializable_{declarationName}.g.cs", SourceText.From(code, Encoding.UTF8));
        Debug.WriteLine($"Created read method for {declarationName}");
    }

    private void BuildReadStatements(
        SourceProductionContext spc,
        SegmentManager segmentManager,
        INamedTypeSymbol classSymbol,
        StringBuilder sb,
        string indent
    ) {
        var fields = classSymbol.GetMembers().OfType<IFieldSymbol>();
        var segmentCount = 0;

        foreach (var field in fields) {
            var fieldType = field.Type;

            if (fieldType.IsPrimitiveLike()) {
                string? magic = null;
                var magicAttributeData = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "MagicAttribute");
                if (magicAttributeData is not null && magicAttributeData.TryGetNamedArg("Magic", out var magicVal)) {
                    magic = magicVal.ToString();
                }

                var fieldDef = new FieldDef(field.Name, fieldType, magic) {
                    ByteSize = fieldType.GetByteSize(),
                };

                segmentManager.AddField(fieldDef);
                DebugUtilities.CreatedFieldDef(fieldDef);
            } else if (fieldType.IsArrayLike(out var arrSymbol)) {
                if (arrSymbol.Rank != 1) throw new NotSupportedException("Arrays which have more than 1 dimension are not supported.");

                var binaryArrayAttr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "BinaryArrayAttribute");
                if (binaryArrayAttr is null) {
                    spc.ReportArrayIsMissingAttribute(field);

                    continue;
                }

                if (!binaryArrayAttr.AreAnyNamedArgsProvided("Size", "SizeMember")) {
                    spc.ReportArrayIsMissingSizeArgument(field);

                    continue;
                }

                if (binaryArrayAttr.AreAllNamedArgsProvided("Size", "SizeMember")) {
                    spc.ReportArrayHasConflictingSizeArguments(field);

                    continue;
                }

                var fieldDef = new FieldDef(field.Name, arrSymbol.ElementType) {
                    TypeModel = {
                        InnerType = arrSymbol.ElementType,
                        InnerTypeByteSize = arrSymbol.ElementType.GetByteSize(),
                    },
                };

                if (binaryArrayAttr.TryGetNamedArg("Size", out var arrSize)) {
                    var arrSizeValue = (int)arrSize.Value!;
                    fieldDef.ByteSize = arrSizeValue * arrSymbol.ElementType.GetByteSize();
                    fieldDef.TypeModel.FixedArraySize = arrSizeValue;

                    DebugUtilities.CreatedFieldDef(fieldDef);
                    segmentManager.AddField(fieldDef);
                } else if (binaryArrayAttr.TryGetNamedArg("SizeMember", out var sizeMember)) {
                    var arrSizeRef = (string)sizeMember.Value!;
                    fieldDef.ByteSize = -1;

                    DebugUtilities.CreatedFieldDef(fieldDef);
                    segmentManager.AddField(fieldDef, arrSizeRef);
                }
            } else if (fieldType.HasBinarySerializableAttribute()) {
                FlushSegments();
                sb.AppendLine($"{indent}result.{field.Name} = {fieldType.Name}.FromBinary(reader);");

                Debug.WriteLine("Built statements for nested object");
            } else {
                spc.ReportUnmarkedSerializableForField(field);
            }
        }

        FlushSegments();

        return;

        void FlushSegments() {
            var segments = segmentManager.Commit();
            foreach (var seg in segments) {
                switch (seg) {
                    case FixedSegment fixedSeg: ProcessFixedSegment(++segmentCount, fixedSeg, sb, indent); break;
                    case DynamicSegment dynSeg: ProcessDynamicSegment(dynSeg, sb, indent); break;
                }
            }

            segmentManager.Clear();
        }
    }

    private void ProcessDynamicSegment(DynamicSegment seg, StringBuilder sb, string indent) {
        foreach (var field in seg.Fields) {
            var elementBytes = field.TypeModel.InnerType!.GetByteSize();
            var bufferName = $"__{field.Name}_buf";

            sb.AppendLine($$"""
                            {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[result.{{seg.LengthReferenceFieldName}}];
                            {{indent}}Span<byte> {{bufferName}} = stackalloc byte[{{elementBytes}} * result.{{seg.LengthReferenceFieldName}}];
                            {{indent}}if (reader.Read({{bufferName}}) < {{elementBytes}} * result.{{seg.LengthReferenceFieldName}}) throw new EndOfStreamException();
                            {{indent}}for (var i = 0; i < result.{{seg.LengthReferenceFieldName}}; i++) {
                            {{indent}}    result.{{field.Name}}[i] = {{field.TypeModel.Type.GetBinaryPrimitiveReader()}}({{bufferName}}.Slice(i * {{elementBytes}}, {{elementBytes}}));
                            {{indent}}}
                            """);
        }
    }

    private void ProcessFixedSegment(int segmentIndex, FixedSegment seg, StringBuilder sb, string indent) {
        var bufName = $"__buf_{segmentIndex}";
        var localOffset = 0;

        sb.AppendLine($"""
                       {indent}Span<byte> {bufName} = stackalloc byte[{seg.Bytes}];
                       {indent}if (reader.Read({bufName}) < {seg.Bytes}) throw new EndOfStreamException();
                       """);

        foreach (var field in seg.Fields) {
            if (field.TypeModel.IsFixedArray) {
                var elementBytes = field.TypeModel.InnerType!.GetByteSize();

                sb.AppendLine($$"""
                                {{indent}}result.{{field.Name}} = new {{field.TypeModel.Type}}[{{field.TypeModel.FixedArraySize!.Value}}];
                                {{indent}}for (var i = 0; i < {{field.TypeModel.FixedArraySize}}; i++) {
                                {{indent}}    result.{{field.Name}}[i] = {{field.TypeModel.Type.GetBinaryPrimitiveReader()}}({{bufName}}.Slice({{localOffset}} + ({{elementBytes}} * i), {{elementBytes}}));
                                {{indent}}}
                                """);

                localOffset += elementBytes * field.TypeModel.FixedArraySize!.Value;

                continue;
            }

            sb.AppendLine($"{indent}result.{field.Name} = {field.TypeModel.Type.GetBinaryPrimitiveReader()}({bufName}.Slice({localOffset}, {field.ByteSize}));");

            localOffset += field.ByteSize;
        }
    }
}